import Layout from 'src/components/Layout'
import SignalList from 'src/components/SignalList'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <h1 className='mx-auto mb-8 max-w-7xl px-4 font-serif text-[calc(1em+8vh)]'>
          Signal
        </h1>
        <div className='container my-10 mx-auto grid grid-cols-1 md:grid-cols-2 md:gap-8'>
          <SignalList />
        </div>
      </Layout>
    </>
  )
}

export default Home
